### ISSUE TITLE
Error After upgrade Xcode to 9.3 (9E145) cannot convert return expression of type '[ArraySlice<TimePeriodProtocol>]' to return type '[AnySequence<TimePeriodProtocol>]'

### ISSUE THREAD

**Issue by castus** [MatthewYork/DateTools#260]
After upgrade Xcode to 9.3 (9E145) i have compilation error in `TimePeriodGroup.swift:105:28`, method `split`

```
Error:(105, 28) cannot convert return expression of type '[ArraySlice<TimePeriodProtocol>]' to return type '[AnySequence<TimePeriodProtocol>]'
```

Can you please fix it?

**Comment by Malecks** [comment]
Also running into this problem

**Comment by tokuduz** [comment]
Hi guys,
I also had an exact same issue, if you are using pods, just update to the newest version. And if you are using DateTools manual install with swift on the link below you will find a solution.

https://github.com/MatthewYork/DateTools/blob/master/DateToolsSwift/DateTools/TimePeriodGroup.swift

An issue that is merged and closed if you want to check it out:
https://github.com/MatthewYork/DateTools/pull/255

**Comment by castus** [comment]
Thanks, it works, issue can be close.
